#ifndef SITUATIONWIDGET_GLOBAL_H
#define SITUATIONWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SITUATIONWIDGET_LIB
# define SITUATIONWIDGET_EXPORT Q_DECL_EXPORT
#else
# define SITUATIONWIDGET_EXPORT Q_DECL_IMPORT
#endif
#endif // SITUATIONWIDGET_GLOBAL_H
